version: "3.8"

services:
  crooner:
    image: agjini/crooner:0.1.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/app/config.toml:ro
      - ./backups:/backups
    restart: unless-stopped
    depends_on:
      - postgres
      - mysql

  postgres:
    image: postgres:15
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  postgres_data:
  mysql_data:
