services:
  crooner:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/app/config.toml:ro
      - ./backup:/backup
    restart: unless-stopped
    depends_on:
      - postgres
      - mysql

  postgres:
    image: postgres:15
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydb
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: my-mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
    restart: unless-stopped
